version: '3'
services:
  oxagile.api:
    build: ./api
    depends_on:
     - oxagile.mssql
    ports:
     - 80:80
    networks:
      - api
  oxagile.mssql:
    image: microsoft/mssql-server-linux:2017-latest
    volumes:
     - oxagile.mssql.data:/var/opt/mssql
    # due to EF Core Migrations we have to manage DB schema somehow (directly?)
    # $ dotnet ef database update
    ports:
     - 1433:1433
    networks:
      - api
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=0PFsE1XMl2e9qzoM5qTj

networks:
  api:
    driver: bridge

volumes:
  oxagile.mssql.data: